# You HAVE to re-build the package to apply changes in this file.
position_start:
  ros__parameters:
    center:
      x: 2
      y: 2.5
    left:
      x: 4
      y: 4
    right:
      x: 2.5
      y: 2
    taco:
      x: 1.01
      y: 0.99