controller_manager:
  ros__parameters:
    update_rate: 150  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    uf850_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController